import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import {fileURLToPath,pathToFileURL} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {PDFDocument}=await import(process.env.PDF_LIB_MODULE || 'pdf-lib');
const root=new URL('../',import.meta.url),out=new URL('test-results/',root);
await mkdir(out,{recursive:true});
const fileURL=new URL('index.html',root).href;
const source=JSON.parse(await readFile(new URL('deck.json',root),'utf8'));
const html=await readFile(new URL('index.html',root));
const server=createServer((req,res)=>{if(req.url?.split('?')[0]==='/tools/presentation-template/'){res.writeHead(200,{'content-type':'text/html'});res.end(html);}else{res.writeHead(404);res.end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const hostedURL=`http://127.0.0.1:${server.address().port}/tools/presentation-template/`;
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
let checks=[];
try {
  const context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true,reducedMotion:'reduce'});
  const page=await context.newPage(),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',request=>{if(/^https?:/.test(request.url())&&!request.url().startsWith(hostedURL))requests.push(request.url());});
  await context.setOffline(true);
  await page.goto(fileURL+'#living-system');
  assert.equal(await page.locator('#deck>.slide:not([hidden])').getAttribute('id'),'living-system');
  for(const id of source.slides.map(s=>s.id)){
    await page.goto(fileURL+'#'+id);
    const canvas=page.locator(`#${id} .canvas`);
    const bounds=await canvas.boundingBox();
    assert.ok(bounds.y>=62&&bounds.y+bounds.height<=951,`${id} must fit above the fold`);
    await canvas.screenshot({path:fileURLToPath(new URL(`${id}.png`,out))});
  }
  checks.push('Offline file opening; stable deep links; seven desktop canvases fit above the fold');
  await page.keyboard.press('Home');await page.locator('#next').click();assert.equal(await page.locator('#deck>.slide:not([hidden])').getAttribute('id'),'precision');
  await page.locator('#overview-open').click();await page.locator('[data-overview="evidence"]').click();assert.equal(await page.locator('#deck>.slide:not([hidden])').getAttribute('id'),'evidence');
  await page.locator('#read-mode').click();assert.equal(await page.locator('#deck>.slide:not([hidden])').count(),7);await page.locator('#read-mode').click();
  await page.locator('#fullscreen').click();assert.equal(await page.evaluate(()=>!!document.fullscreenElement),true);await page.locator('#fullscreen').click();
  await page.locator('#motion').click();assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('paused')),true);
  checks.push('Navigation, overview, reading mode, fullscreen enter/exit, and pause motion');
  await page.keyboard.press('Home');await page.locator('#edit-mode').click();
  const editorCanvas=await page.locator('#the-fold .canvas').boundingBox();assert.ok(editorCanvas.x>=350,'Editor must not cover desktop canvas');
  await page.locator('[name=title]').fill('An edited headline.\nA durable change.');await page.locator('.apply').click();
  assert.match(await page.locator('#the-fold h1').innerText(),/An edited headline/);
  await page.locator('#undo').click();assert.match(await page.locator('#the-fold h1').innerText(),/Make the point/);
  await page.locator('#redo').click();assert.match(await page.locator('#the-fold h1').innerText(),/An edited headline/);
  await page.locator('[data-id="the-fold"][data-move="1"]').click();assert.equal(await page.locator('.slide-row').nth(1).getAttribute('data-id'),'the-fold');
  const rows=page.locator('.slide-row');
  await rows.filter({has:page.locator('[data-select="your-turn"]')}).dragTo(rows.filter({has:page.locator('[data-select="precision"]')}),{targetPosition:{x:30,y:3}});
  assert.equal(await page.locator('.slide-row').first().getAttribute('data-id'),'your-turn');
  checks.push('Rendered editor changes, undo/redo, keyboard-button reorder, and drag reorder');
  const jsonDownload=page.waitForEvent('download');await page.locator('#download-json').click();const jsonPath=fileURLToPath(new URL('edited.json',out));await (await jsonDownload).saveAs(jsonPath);
  const edited=JSON.parse(await readFile(jsonPath,'utf8'));assert.equal(edited.slides[0].id,'your-turn');assert.match(edited.slides.find(s=>s.id==='the-fold').title,/An edited headline/);
  const htmlDownload=page.waitForEvent('download');await page.locator('#download-html').click();const htmlPath=fileURLToPath(new URL('edited.html',out));await (await htmlDownload).saveAs(htmlPath);
  const reopened=await context.newPage();await reopened.goto(pathToFileURL(htmlPath).href);assert.equal(await reopened.locator('#deck>.slide').first().getAttribute('id'),'your-turn');assert.match(await reopened.locator('#the-fold h1').textContent(),/An edited headline/);await reopened.close();
  await page.reload();assert.equal(await page.locator('#draft-banner').isVisible(),true);await page.locator('#restore-draft').click();await page.locator('#edit-mode').click();assert.equal(await page.locator('.slide-row').first().getAttribute('data-id'),'your-turn');
  checks.push('JSON and standalone HTML exports retain edits/order; downloaded HTML reopens offline; browser draft restores');
  await page.locator('#json-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":99}')});
  await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('Could not open'));
  assert.equal(await page.locator('.slide-row').count(),7);
  await page.locator('#json-file').setInputFiles({name:'source.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(source))});
  await page.waitForFunction(()=>document.querySelector('.slide-row')?.dataset.id==='the-fold');
  const literal=structuredClone(source);literal.slides[0].title='<img src=x onerror=alert(1)>';
  await page.locator('#json-file').setInputFiles({name:'literal.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(literal))});
  await page.waitForFunction(()=>document.querySelector('#the-fold h1').textContent.startsWith('<img'));
  assert.equal(await page.locator('#the-fold h1 img').count(),0);
  await page.locator('#undo').click();await page.locator('#close-editor').click();
  checks.push('Malformed import preserves current deck; imported markup is rendered as text');
  await page.emulateMedia({media:'print'});
  const slidesPDF=await page.pdf({preferCSSPageSize:true,printBackground:true,path:fileURLToPath(new URL('slides.pdf',out))});
  const slidesDoc=await PDFDocument.load(slidesPDF);assert.equal(slidesDoc.getPageCount(),7,'Slides-only PDF must have seven pages');
  await page.evaluate(()=>document.body.classList.add('print-details'));
  const detailPDF=await page.pdf({preferCSSPageSize:true,printBackground:true,path:fileURLToPath(new URL('slides-and-details.pdf',out))});
  const detailsDoc=await PDFDocument.load(detailPDF);assert.equal(detailsDoc.getPageCount(),14,'Each example has one canvas and one detail page');
  checks.push('PDF exports: seven slides-only pages and fourteen slides-plus-details pages');
  await page.emulateMedia({media:'screen'});await page.evaluate(()=>document.body.classList.remove('print-details'));
  await page.setViewportSize({width:390,height:844});
  for(const id of source.slides.map(s=>s.id)){
    await page.goto(fileURL+'#'+id);if(await page.locator('#draft-banner').isVisible())await page.locator('#dismiss-draft').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${id}: no mobile horizontal overflow`);
    const bad=await page.locator(`#${id} .canvas`).evaluate(el=>{const parent=el.getBoundingClientRect();return [...el.querySelectorAll('.slide-copy,.art,.chart,.type-steps,.editorial-items,.iso-legend,.system-caption')].filter(x=>{const r=x.getBoundingClientRect();return r.width&&r.height&&(r.bottom>parent.bottom+1||r.right>parent.right+1||r.left<parent.left-1);}).map(x=>x.className);});
    assert.deepEqual(bad,[],`${id}: content must stay inside the canvas`);
    await page.screenshot({path:fileURLToPath(new URL(`mobile-${id}.png`,out)),fullPage:true});
  }
  checks.push('All seven mobile layouts: no horizontal overflow or clipped major content regions');
  await context.setOffline(false);await page.setViewportSize({width:1280,height:800});await page.goto(hostedURL+'#precision');assert.equal(await page.locator('#deck>.slide:not([hidden])').getAttribute('id'),'precision');
  await page.locator('#edit-mode').click();await page.locator('[name=title]').fill('Hosted editing works.');await page.locator('.apply').click();assert.equal(await page.locator('#precision h1').textContent(),'Hosted editing works.');
  checks.push('Hosted subfolder opening and editing');
  assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
  await context.close();
  const blocked=await browser.newContext();await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage disabled','SecurityError');}}));const p=await blocked.newPage();await p.goto(fileURL);await p.locator('#edit-mode').click();await p.locator('[name=title]').fill('No storage required.');await p.locator('.apply').click();assert.match(await p.locator('#save-status').textContent(),/storage unavailable/);const dl=p.waitForEvent('download');await p.locator('#download-html').click();await (await dl).saveAs(fileURLToPath(new URL('storage-disabled.html',out)));await blocked.close();
  checks.push('Storage-denied recovery: edit and download still work');
  await writeFile(new URL('verification.json',out),JSON.stringify({verifiedAt:new Date().toISOString(),browser:browser.version(),checks,pageErrors:errors,externalRequests:requests},null,2));
  console.log(checks.map(x=>'PASS: '+x).join('\n'));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
